export const TMDB_GENRES = [
  'Action',
  'Adventure',
  'Animation',
  'Comedy',
  'Crime',
  'Documentary',
  'Drama',
  'Family',
  'Fantasy',
  'History',
  'Horror',
  'Music',
  'Mystery',
  'Romance',
  'Science Fiction',
  'TV Movie',
  'Thriller',
  'War',
  'Western',
] as const;

export const GENRE_TRANSLATIONS: Record<string, string> = {
  'Action': 'Боевик',
  'Adventure': 'Приключения',
  'Animation': 'Анимация',
  'Comedy': 'Комедия',
  'Crime': 'Криминал',
  'Documentary': 'Документальный',
  'Drama': 'Драма',
  'Family': 'Семейный',
  'Fantasy': 'Фэнтези',
  'History': 'Исторический',
  'Horror': 'Ужасы',
  'Music': 'Музыка',
  'Mystery': 'Мистика',
  'Romance': 'Мелодрама',
  'Science Fiction': 'Научная фантастика',
  'TV Movie': 'Телефильм',
  'Thriller': 'Триллер',
  'War': 'Военный',
  'Western': 'Вестерн',
};

/**
 * Reverse translations: Russian → English.
 * Includes both title-case and lowercase variants since TMDB
 * returns genre names in different cases depending on context.
 * Also includes additional genres that TMDB returns for TV shows.
 */
export const GENRE_REVERSE_TRANSLATIONS: Record<string, string> = {
  // Title-case variants
  'Боевик': 'Action',
  'Приключения': 'Adventure',
  'Анимация': 'Animation',
  'Комедия': 'Comedy',
  'Криминал': 'Crime',
  'Документальный': 'Documentary',
  'Драма': 'Drama',
  'Семейный': 'Family',
  'Фэнтези': 'Fantasy',
  'Исторический': 'History',
  'Ужасы': 'Horror',
  'Музыка': 'Music',
  'Мистика': 'Mystery',
  'Мелодрама': 'Romance',
  'Научная фантастика': 'Science Fiction',
  'Телефильм': 'TV Movie',
  'Триллер': 'Thriller',
  'Военный': 'War',
  'Вестерн': 'Western',
  // Lowercase variants (TMDB returns these for ru-RU)
  'боевик': 'Action',
  'приключения': 'Adventure',
  'анимация': 'Animation',
  'мультфильм': 'Animation',
  'комедия': 'Comedy',
  'криминал': 'Crime',
  'документальный': 'Documentary',
  'драма': 'Drama',
  'семейный': 'Family',
  'фэнтези': 'Fantasy',
  'исторический': 'History',
  'ужасы': 'Horror',
  'музыка': 'Music',
  'мистика': 'Mystery',
  'мелодрама': 'Romance',
  'научная фантастика': 'Science Fiction',
  'фантастика': 'Science Fiction',
  'телефильм': 'TV Movie',
  'триллер': 'Thriller',
  'военный': 'War',
  'вестерн': 'Western',
  'детектив': 'Mystery',
  'новости': 'News',
  'реалити': 'Reality',
  'soap': 'Soap',
  'ток-шоу': 'Talk',
  'war & politics': 'War & Politics',
};
